#
# Copyright (c) 2017 Bitprim developers (see AUTHORS)
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


# ------------------------------------------------------------------------------------------------------


build: false

environment:
    # VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"

    matrix:
      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "8"

      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "7"

      - WINDOWS_SDK_VERSION: "v7.1"
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        nodejs_version: "6"
  


install:

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # - npm install
  - npm --version
  - npm install -g node-gyp
  - npm install -g node-pre-gyp
  - npm install -g aws-sdk
  - npm install -g node-pre-gyp-github
  

  # - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  # - SET VS90COMNTOOLS=%VS140COMNTOOLS%
  # - cd "c:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\"
  # - ren "Visual C++ for Python" "Visual C++ for Python Do Not Use"
  # - cd "C:\Program Files (x86)\"
  # - ren "Microsoft Visual Studio 9.0" "Microsoft Visual Studio 9.0 Do Not Use"
  # - cp "c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\stdint.h" "C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\include\stdint.h"


  - pip --version
  - pip install conan --upgrade
  - python --version
  - conan user # It creates the conan data directory


before_build:
  # - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  # - IF "%PYTHON_ARCH%"=="64" (
  #     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  #   ) ELSE (
  #     call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  #   )


# test_script:
build_script:
  - node --version
  - npm --version
  - python --version
  # - cl /version
  - conan user
  - conan remote add bitprim_temp https://api.bintray.com/conan/bitprim/bitprim
  # - conan install .

  - npm install
  # - node-pre-gyp configure build package
  - node-pre-gyp configure --verbose
  - node-pre-gyp build --verbose
  - node-pre-gyp package --verbose
  - node-pre-gyp-github publish --release  || true
  
    # - cd %APPVEYOR_BUILD_FOLDER% 
    # - conan install .
    # # - pip install  -e .
    # - "%PYTHON%\\python.exe setup.py build"
    # - "%PYTHON%\\python.exe setup.py sdist"
    # - "%PYTHON%\\python.exe setup.py bdist_wheel"

    # - IF "%APPVEYOR_REPO_BRANCH%"=="master" (
    #     twine upload -u %PYPI_USER_NAME% -p %PYPI_PASSWORD% dist/* || true
    #   ) ELSE (
    #     twine upload -u %PYPI_USER_NAME% -p %PYPI_PASSWORD% --repository-url https://test.pypi.org/legacy/ dist/*  || true
    #   )


